### ISSUE TITLE
Where is AuthenticationProvider Defined?

### ISSUE THREAD

**Issue by mastermindg** [virtualforce/Devise-Omniauth-Multiple-Providers#1]
Running the second migrate causes:

NameError: uninitialized constant AuthenticationProvider

I checked Devise and OmniAuth and I don't see any references to a class or module with this name.

**Comment by muhammadumarkhan-vf** [comment]
For this, you need to create models for authentication_provider and user_authentication.
1) run "rails generate model authentication_provider"
2) run "rails generate model user_authentication"
3) run "rake db:migrate"

hope this helps

**Comment by muhammadumarkhan-vf** [comment]
For this, you need to create models for authentication_provider and user_authentication.
1) run "rails generate model authentication_provider"
2) run "rails generate model user_authentication"
2) run "rake db:migrate"

hope this helps
