### ISSUE TITLE
NoMethodError in Users::OmniauthCallbacksController#facebook

### ISSUE THREAD

**Issue by ja-camus** [virtualforce/Devise-Omniauth-Multiple-Providers#2]
Hello!
I was following your tutorial on `Rails 5`.
Doing it step by step (creating the migrations manually with "`rails generate model authentication_provider`" and "`rails generate model user_authentication`") shows me an error of this type:

```
NoMethodError in Users :: OmniauthCallbacksController # facebook
undefined method `get_provider_name 'for # <Class: 0x007fc774e93ae8> Did you mean? get_primary_key
```

Do you have any idea what it can be? : c
Thanks since now!

**Comment by fakhir-shad** [comment]
Hi There!
Sorry for the inconvenience, `get_provider_name' scope is missing. I have updated the tutorial, please follow it again step by step. Let me know if the issue still persists
